{% set name = "nd2reader" %}
{% set version = "3.3.0" %}
{% set sha256 = "41db1048e19e6b6161aea990df29e264121cde1e1a98df6ca785ebefff184ff9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --no-cache-dir -vvv ."

requirements:
  build:
    - python >=3.6
    - setuptools
    - numpy >=1.6.2
    - six >=1.4
    - xmltodict >=0.9.2
    - pims >=0.3.0
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - numpy >=1.6.2
    - six >=1.4
    - xmltodict >=0.9.2
    - pims >=0.3.0
  run:
    - python >={{ python_min }}
    - numpy >=1.6.2
    - six >=1.4
    - xmltodict >=0.9.2
    - pims >=0.3.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - nd2reader

about:
  home: https://github.com/rbnvrw/nd2reader
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Pure Python library for reading NIS Elements ND2 images and metadata'
  description: |
    nd2reader is a pure-Python package that reads images produced by NIS Elements 4.0+. It has 
    only been definitively tested on NIS Elements 4.30.02 Build 1053. Support for older versions 
    is being actively worked on. The reader is written in the pims framework, enabling easy 
    access to multidimensional files, lazy slicing, and nice display in IPython.
  doc_url: http://www.lighthacking.nl/nd2reader/
  dev_url: https://github.com/rbnvrw/nd2reader/

extra:
  recipe-maintainers:
    - rbnvrw
    - caspervdw
